// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sample

import (
	"github.com/google/go-cloud/wire"
)

// Injectors from injector.go:

func initStore() (*Store, error) {
	item := NewOKItem()
	store, err := NewStore(item)
	if err != nil {
		return nil, err
	}
	return store, nil
}

// injector.go:

var storeSet = wire.NewSet(NewOKItem, NewStore)
